apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: newnamespace
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/abc/codebase-repo:0f24835465c9e39c2481a74b3bf8aeeedcc52704
          ports:
            - containerPort: 80
