kind: Service
apiVersion: v1
metadata:
  name: dev-gitops-demo
  namespace: newnamespace
spec:
  ports:
    - name: http1
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: dev-gitops-demo
  type: ClusterIP
status:
  loadBalancer: {}
